language: cpp 

os: linux 
dist: xenial 

compiler:
  - g++

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -q update
  - sudo apt-get -y install g++-7

script:
  - cmake --version
  - bash vcpkg/bootstrap-vcpkg.sh
  - mkdir build 
  - cd build
  - cmake ..