language: cpp 

os: linux 
dist: xenial 
addons:
  apt:
    sources:
      - ppa:chris-lea/redis-server
    packages:
      - g++-7

compiler:
  - g++

before_install:
  - cmake --version
  - bash vcpkg/bootstrap-vcpkg.sh
  - mkdir build 
  - cd build
  - cmake ..