language: cpp 
compiler:
  - g++

os: linux 
dist: xenial 
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essentials 

script:
  - ls
  - make --version
  - mkdir build 
  - cd build
  - cmake ..