language: cpp 
compiler:
  - g++

os: linux 
dist: xenial 
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - build-essential 

before_install:
  - bash ./setup.sh

script:
  - mkdir build 
  - cd build
  - cmake ..
