language: cpp 
compiler:
  - g++

os: linux 
dist: xenial 
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

script:
  - bash vcpkg/vcpkg list
  - make --version
  - mkdir build 
  - cd build
  - cmake ..