enum Category {
    TERRAIN =  0x0001,
    PLAYER =   0x0002,
    ENEMY =    0x0004,
    PARTICLE = 0x0008,
};

/*enum Keycode{
    Key_A = "A",
    Key_B = "B",
    Key_C = "C",
    Key_D = "D",
    Key_E = "E",
    Key_F = "F",
    Key_G = "G",
    Key_H = "H",
    Key_I = "I",
    Key_J = "J",
    Key_K = "K",
    Key_L = "L",
    Key_N = "N",
    Key_M = "M",
    Key_O = "O",
    Key_P = "P",
    Key_Q = "Q",
    Key_R = "R",
    Key_S = "S",
    Key_T = "T",
    Key_U = "U",
    Key_V = "V",
    Key_W = "W",
    Key_X = "X",
    Key_Y = "Y",
    Key_Z = "Z",
}*/
